PLANTS = [
    {"id": "P01", "kind": "plant", "name": "Arbusto de bayas", "cnPerTurn": 1},
    {"id": "P02", "kind": "plant", "name": "Helecho denso", "cnPerTurn": 1},
    {"id": "P03", "kind": "plant", "name": "Árbol joven", "cnPerTurn": 2},
    {"id": "P04", "kind": "plant", "name": "Hongos micelio", "cnPerTurn": 1},
    {"id": "P05", "kind": "plant", "name": "Pradera clara", "cnPerTurn": 2},
]

ANIMALS = [
    # Nivel 1
    {
        "id": "A01",
        "kind": "animal",
        "name": "Escarabajo detritívoro",
        "type": "Herbivore",
        "level": 1,
        "attack": 4,
        "defense": 8,
        "mobility": 18,
        "instinct": 12,
        "weightKg": 0.02,
    },
    {
        "id": "A02",
        "kind": "animal",
        "name": "Ratón de campo",
        "type": "Herbivore",
        "level": 1,
        "attack": 6,
        "defense": 10,
        "mobility": 28,
        "instinct": 22,
        "weightKg": 0.03,
    },
    {
        "id": "A03",
        "kind": "animal",
        "name": "Lagartija rápida",
        "type": "Omnivore",
        "level": 1,
        "attack": 10,
        "defense": 10,
        "mobility": 35,
        "instinct": 25,
        "weightKg": 0.05,
    },
    # Nivel 2
    {
        "id": "A04",
        "kind": "animal",
        "name": "Conejo europeo",
        "type": "Herbivore",
        "level": 2,
        "attack": 10,
        "defense": 18,
        "mobility": 42,
        "instinct": 35,
        "weightKg": 2.5,
    },
    {
        "id": "A05",
        "kind": "animal",
        "name": "Pato silvestre",
        "type": "Omnivore",
        "level": 2,
        "attack": 14,
        "defense": 16,
        "mobility": 38,
        "instinct": 28,
        "weightKg": 1.2,
    },
    {
        "id": "A06",
        "kind": "animal",
        "name": "Zorro joven",
        "type": "Carnivore",
        "level": 2,
        "attack": 28,
        "defense": 20,
        "mobility": 45,
        "instinct": 40,
        "weightKg": 6.0,
    },
    # Nivel 3
    {
        "id": "A07",
        "kind": "animal",
        "name": "Corzo",
        "type": "Herbivore",
        "level": 3,
        "attack": 18,
        "defense": 30,
        "mobility": 52,
        "instinct": 44,
        "weightKg": 25.0,
    },
    {
        "id": "A08",
        "kind": "animal",
        "name": "Jabalí",
        "type": "Omnivore",
        "level": 3,
        "attack": 30,
        "defense": 40,
        "mobility": 36,
        "instinct": 38,
        "weightKg": 70.0,
    },
    {
        "id": "A09",
        "kind": "animal",
        "name": "Lince ibérico",
        "type": "Carnivore",
        "level": 3,
        "attack": 44,
        "defense": 30,
        "mobility": 55,
        "instinct": 58,
        "weightKg": 12.0,
    },
    # Nivel 4
    {
        "id": "A10",
        "kind": "animal",
        "name": "Ciervo rojo",
        "type": "Herbivore",
        "level": 4,
        "attack": 28,
        "defense": 52,
        "mobility": 48,
        "instinct": 46,
        "weightKg": 160.0,
    },
    {
        "id": "A11",
        "kind": "animal",
        "name": "Oso pardo (omnívoro)",
        "type": "Omnivore",
        "level": 4,
        "attack": 55,
        "defense": 60,
        "mobility": 34,
        "instinct": 50,
        "weightKg": 220.0,
    },
    {
        "id": "A12",
        "kind": "animal",
        "name": "Lobo gris",
        "type": "Carnivore",
        "level": 4,
        "attack": 58,
        "defense": 44,
        "mobility": 50,
        "instinct": 54,
        "weightKg": 40.0,
    },
    # Nivel 5
    {
        "id": "A13",
        "kind": "animal",
        "name": "Alce",
        "type": "Herbivore",
        "level": 5,
        "attack": 40,
        "defense": 70,
        "mobility": 38,
        "instinct": 50,
        "weightKg": 500.0,
    },
    {
        "id": "A14",
        "kind": "animal",
        "name": "Oso pardo dominante",
        "type": "Carnivore",
        "level": 5,
        "attack": 70,
        "defense": 72,
        "mobility": 30,
        "instinct": 55,
        "weightKg": 320.0,
    },
    # Nivel 6
    {
        "id": "A15",
        "kind": "animal",
        "name": "Apex: Tigre (histórico)",
        "type": "Carnivore",
        "level": 6,
        "attack": 85,
        "defense": 65,
        "mobility": 60,
        "instinct": 78,
        "weightKg": 240.0,
    },
    {
        "id": "A16",
        "kind": "animal",
        "name": "Gigaherbívoro: Bisonte gigante",
        "type": "Herbivore",
        "level": 6,
        "attack": 55,
        "defense": 85,
        "mobility": 28,
        "instinct": 52,
        "weightKg": 900.0,
    },
]

DECK_P1 = [
    # plantas (8)
    "P01",
    "P01",
    "P02",
    "P02",
    "P03",
    "P03",
    "P04",
    "P05",
    # base niveles bajos (14)
    "A01",
    "A01",
    "A02",
    "A02",
    "A03",
    "A03",
    "A04",
    "A04",
    "A05",
    "A05",
    "A06",
    "A06",
    "A07",
    "A08",
    # medios/altos (8-10)
    "A09",
    "A10",
    "A10",
    "A11",
    "A12",
    "A12",
    "A13",
    "A14",
    "A16",
    "A15",
]

DECK_P2 = [
    # plantas (8)
    "P01",
    "P02",
    "P02",
    "P03",
    "P03",
    "P04",
    "P04",
    "P05",
    # base niveles bajos (14)
    "A01",
    "A02",
    "A02",
    "A03",
    "A03",
    "A04",
    "A04",
    "A05",
    "A05",
    "A06",
    "A06",
    "A07",
    "A07",
    "A08",
    # medios/altos (8-10)
    "A09",
    "A09",
    "A10",
    "A11",
    "A11",
    "A12",
    "A13",
    "A14",
    "A16",
    "A15",
]

CARD_INDEX = {card["id"]: card for card in PLANTS + ANIMALS}
